### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by ghost** [hao-ua/aws_inventory#3]
Traceback (most recent call last):
  File "aws_inventory.py", line 74, in <module>
    main()
  File "aws_inventory.py", line 44, in main
    data_priority[inst.Priority] = inst.Name

**Comment by ghost** [comment]
(venv) python aws_inventory.py
Traceback (most recent call last):
  File "aws_inventory.py", line 74, in <module>
    main()
  File "aws_inventory.py", line 48, in main
    items[name] = data[name].get_data()
  File "/home/xxx/xxx/xxx/aws_inventory/data_Route53.py", line 46, in get_data
    zone = self.get_all_items(credential[0], credential[1])
  File "/home/xxx/xxxx/xxx/aws_inventory/data_Route53.py", line 19, in get_all_items
    res = conn.get_all_hosted_zones()
  File "/home/cloudsec/xxx/xxxx/xxx/venv/lib/python2.7/site-packages/boto/route53/connection.py", line 126, in get_all_hosted_zones
    body)
boto.route53.exception.DNSServerError: DNSServerError: 403 Forbidden
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>MissingAuthenticationToken</Code><Message>Request is missing Authentication Token</Message></Error><RequestId>a80d35e1-89f9-11e8-a015-8df86eaf1dbe</RequestId></ErrorResponse>
